name: Continuous Deployment (CD)

on:
  workflow_run:
    workflows:
      - "Continous Integration (CI)"
    branches:
      - main
    types:
      - completed

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v1
        with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-order/heymart-order .

      - name: Push
        run: |
          docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-order/heymart-order

      - name: Deploy
        run: |
          gcloud run deploy heymart-order \
          --region asia-southeast2 \
          --image asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/heymart-order/heymart-order \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --set-env-vars=PG_HOST=${{ secrets.PG_HOST }} \
          --set-env-vars=PG_DB=${{ secrets.PG_USERNAME }} \
          --set-env-vars=PG_USER=${{ secrets.PG_PASSWORD }} \